RealEstate/RealEstate/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RealEstate.Models;
using RealEstate.ViewModels;

namespace RealEstate.Controllers;

public class HomeController : Controller
{
    private readonly UserManager <AppUser> _userManager;
     private readonly RealEstateContext _context;

    public HomeController(UserManager<AppUser> userManager,RealEstateContext context)
    {
         _context = context;
        _userManager = userManager;
    }

public ActionResult AdForwarding()
{
    return View();
}
    public async Task  <IActionResult> Index( )
    {
     
        var house = await _context.Houses
        .Where(h => h.Active == "true")
        .Take(8)
        .ToListAsync();
        
         var plot = await _context.Plots
        .Where(h => h.Active == "true")
        .Take(8)
        .ToListAsync();

        
        var viewmodel = new RealEstateViewModel{
            
            HouseList = house,
            PlotList = plot
        };
        return View(viewmodel);
    }


 
}

RealEstate/RealEstate/Controllers/HouseController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using RealEstate.Entity;
using RealEstate.Models;
using RealEstate.ViewModels;
using RealEstate.ViewModels.Housee;
using RealEstate.ViewModels.User;


namespace RealEstate.Controllers
{

    public class HouseController : Controller
    {
        private readonly RealEstateContext _context;
        private readonly UserManager<AppUser> _userManager;
        public HouseController(RealEstateContext context,
       UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        [HttpGet]
        [Authorize]
        public  async Task <IActionResult> HouseAdd(UserViewModel model)
        {
          
                return View();
            
        }
 [HttpPost]
   [Authorize]
public async Task<IActionResult> HouseAdd(HouseViewModel model)
{
    if (ModelState.IsValid)
    {
        
        var currentUser = await _userManager.GetUserAsync(User);

        var house = new House
        {
            AdType = model.AdType,
            AdNumber = Guid.NewGuid(),
            HouseType = model.HouseType,
            Price = model.Price,
            m2b = model.m2b,
            m2n = model.m2n,
            NumberOfRooms = model.NumberOfRooms,
            BuildingHistory = model.BuildingHistory,
            NumberOfFloors = model.NumberOfFloors,
            Floor = model.Floor,
            Heating = model.Heating,
            Elevator = model.Elevator,
            CarPark = model.CarPark,
            AnnouncementDate = DateTime.Now,
            Dues = model.Dues,
            Explanation = model.Explanation,
            Country = model.Country,
            Province = model.Province,
            County = model.County,
            Neighborhood = model.Neighborhood,
            Street = model.Street,
            Active = "newAd",
            AdStatus=model.AdStatus,
            AdTitle = model.AdTitle,
            AppUserId = currentUser?.Id, 
            HouseImages = new List<HouseImg>()
        };

        if (model.PromotionalPicture != null && model.PromotionalPicture.Length > 0)
        {
            var fileName = Path.GetFileName(model.PromotionalPicture.FileName);
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await model.PromotionalPicture.CopyToAsync(stream);
            }

            house.PromotionalPicture = $"/images/{fileName}";
        }

        if (model.Images != null && model.Images.Count > 0)
        {
            foreach (var image in model.Images)
            {
                if (image != null && image.Length > 0)
                {
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images", fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }

                    house.HouseImages.Add(new HouseImg
                    {
                        ImgUrl = $"/images/{fileName}"
                    });
                }
            }
        }

        _context.Houses.Add(house);
        await _context.SaveChangesAsync();

        return RedirectToAction("Index","Home"); 
    }

    return View(model);
}

  public async Task<IActionResult> HouseDetails(int id)
{
    var house = await _context.Houses
                              .Include(h => h.HouseImages)
                              .Include(h => h.AppUser) 
                              .FirstOrDefaultAsync(h => h.HouseId == id);
                              

    if (house == null)
    {
        return NotFound();
    }

    var viewModel = new RealEstateViewModel
    {
        House = house,
        HouseImages = house.HouseImages?.ToList()
    };

    return View(viewModel);
}


    public async Task<IActionResult> HouseList()
    {

        
       // İlk sayfa yüklendiğinde tüm evleri getiriyoruz
        var model = new HouseFilterViewModel
        {
            HouseList = _context.Houses.ToList()
        };

        return View(model);
    }
     [HttpPost]
    public IActionResult Filter(HouseFilterViewModel model)
    {
        // Filtreleme işlemi
        var filteredHouses = _context.Houses.AsQueryable();

        if (!string.IsNullOrEmpty(model.County))
        {
            filteredHouses = filteredHouses.Where(h => h.County == model.County);
        }

        if (!string.IsNullOrEmpty(model.PriceRange))
        {
            var priceRange = model.PriceRange.Split('-');
            if (priceRange.Length == 2)
            {
                if (decimal.TryParse(priceRange[0], out var minPrice) && decimal.TryParse(priceRange[1], out var maxPrice))
                {
                    filteredHouses = filteredHouses.Where(h => decimal.Parse(h.Price) >= minPrice && decimal.Parse(h.Price) <= maxPrice);
                }
            }
        }

        if (!string.IsNullOrEmpty(model.NumberOfRooms))
        {
            filteredHouses = filteredHouses.Where(h => h.NumberOfRooms == model.NumberOfRooms);
        }

        if (!string.IsNullOrEmpty(model.AdType))
        {
            filteredHouses = filteredHouses.Where(h => h.AdType == model.AdType);
        }

        if (!string.IsNullOrEmpty(model.CarPark))
        {
            filteredHouses = filteredHouses.Where(h => h.CarPark == model.CarPark);
        }

        // Filtrelenmiş evleri model'e ekliyoruz
        model.HouseList = filteredHouses.ToList();

        return View("HouseList", model);
    }
    

[HttpGet]
  [Authorize]
public async Task<IActionResult>HouseEdit(int id)
{
    var house = await _context.Houses.FindAsync(id);
    if (house == null)
    {
        return NotFound();
    }
    var existingImages = house.HouseImages?.Select(img => img.ImgUrl).ToList();

    var model = new HouseEditViewModel
    {
        AdType = house.AdType,
        HouseType = house.HouseType,
        AdTitle = house.AdTitle,
        Price = house.Price,
        m2b = house.m2b,
        m2n = house.m2n,
        AdStatus = house.AdStatus,
        NumberOfRooms = house.NumberOfRooms,
        BuildingHistory = house.BuildingHistory,
        NumberOfFloors = house.NumberOfFloors,
        Floor = house.Floor,
        Heating = house.Heating,
        Elevator = house.Elevator,
        CarPark = house.CarPark,
        Dues = house.Dues,
        Explanation = house.Explanation,
        Country = house.Country,
        Province = house.Province,
        County = house.County,
        Neighborhood = house.Neighborhood,
        Street = house.Street,

    };
    return View(model);
}

[HttpPost]
[ValidateAntiForgeryToken]
public async Task<IActionResult> HouseEdit(int id, HouseEditViewModel model)
{
    var house = await _context.Houses.FindAsync(id);
    if (house == null)
    {
        return NotFound();
    }

    if (ModelState.IsValid)
    {
        house.AdType = model.AdType;
        house.HouseType = model.HouseType;
        house.AdTitle = model.AdTitle;
        house.Price = model.Price;
        house.m2b = model.m2b;
        house.m2n = model.m2n;
        house.AdStatus = model.AdStatus;
        house.NumberOfRooms = model.NumberOfRooms;
        house.BuildingHistory = model.BuildingHistory;
        house.NumberOfFloors = model.NumberOfFloors;
        house.Floor = model.Floor;
        house.Heating = model.Heating;
        house.Elevator = model.Elevator;
        house.CarPark = model.CarPark;
        house.Dues = model.Dues;
        house.Explanation = model.Explanation;
        house.Country = model.Country;
        house.Province = model.Province;
        house.County = model.County;
        house.Neighborhood = model.Neighborhood;
        house.PromotionalPicture = house.PromotionalPicture;
        house.Street = model.Street;
        house.Active = "newAd";

       

        _context.Houses.Update(house);
        await _context.SaveChangesAsync();
        return RedirectToAction("MyAd", "Identity");
    }

    return View(model);
}



}
}

RealEstate/RealEstate/Controllers/PlotController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using RealEstate.Entity;
using RealEstate.Models;
using RealEstate.ViewModels;
using RealEstate.ViewModels.Plot;
using Microsoft.EntityFrameworkCore;
using RealEstate.ViewModels.Plot;


namespace RealEstate.Controllers
{
    public class PlotController : Controller
    {
        private readonly RealEstateContext _context;
         private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;
    public  PlotController
    (
         RealEstateContext context,
        UserManager<AppUser> userManager,
        RoleManager<AppRole> roleManager
        ){
              {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }}
         public async Task<IActionResult>PlotAdd()
        {
             var user = await _userManager.GetUserAsync(User);
            if (User.Identity.IsAuthenticated)
            {
                return View();
            }
            return View();
        }

[HttpPost]
[Authorize]
public async Task<IActionResult> PlotAdd(PlotCreateViewModel model)
{
    if (ModelState.IsValid)
    {
        var user = await _userManager.GetUserAsync(User);
        var plot = new Plot
        {
            AdNumber = Guid.NewGuid(),
            PlotType = model.PlotType,
            PlotPrice = model.PlotPrice,
            PlotTitle = model.PlotTitle,
            M2 = model.M2,
            M2Price = model.M2Price,
            TitleDeedStatus = model.TitleDeedStatus,
            IslandNumber = model.IslandNumber,
            ParcelNumber = model.ParcelNumber,
            Country = model.Country,
            Province = model.Province,
            AnnouncementDate = DateTime.Now,
            Active = "newAd",
            PlotStatus = model.PlotStatus,
            County = model.County,
            AdType = model.AdType,
            Explanation = model.Explanation,
            Neighborhood = model.Neighborhood,
            Street = model.Street,
            CreditEligibility = model.CreditEligibility,
            PromotionalPicture = model.PromotionalPicture?.FileName,
            PlotImages = new List<PlotImages>(),
            AppUserId = user?.Id
        };
        if (model.plotImages != null && model.plotImages.Any())
        {
            var uploadFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/plotimages");

            if (!Directory.Exists(uploadFolder))
            {
                Directory.CreateDirectory(uploadFolder);
            }
            foreach (var file in model.plotImages)
            {
                if (file.Length > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var filePath = Path.Combine(uploadFolder, fileName);
                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                    plot.PlotImages.Add(new PlotImages { ImgUrl = fileName });
                }
            }
        }
        _context.Plots.Add(plot);
        await _context.SaveChangesAsync();

        return RedirectToAction("MyAd", "Identity");
    }

    return View(model);
}

public async Task<IActionResult> PlotList()
    {
        
         var model = new PlotFilterViewModel
        {
           PlotList = _context.Plots.ToList()
        };

        return View(model);
    }
     [HttpPost]
    public IActionResult Filter(PlotFilterViewModel model)
    {
        var filteredPlots = _context.Plots.AsQueryable();

        if (!string.IsNullOrEmpty(model.County))
        {
            filteredPlots = filteredPlots.Where(h => h.County == model.County);
        }

        if (!string.IsNullOrEmpty(model.PriceRange))
        {
            var priceRange = model.PriceRange.Split('-');
            if (priceRange.Length == 2)
            {
                if (decimal.TryParse(priceRange[0], out var minPrice) && decimal.TryParse(priceRange[1], out var maxPrice))
                {
                    filteredPlots = filteredPlots.Where(h => decimal.Parse(h.PlotPrice) >= minPrice && decimal.Parse(h.PlotPrice) <= maxPrice);
                }
            }
        }

        if (!string.IsNullOrEmpty(model.County))
        {
            filteredPlots = filteredPlots.Where(h => h.County == model.County);
        }

        if (!string.IsNullOrEmpty(model.TitleDeedStatus))
        {
            filteredPlots = filteredPlots.Where(h => h.TitleDeedStatus == model.TitleDeedStatus);
        }

        if (!string.IsNullOrEmpty(model.CreditEligibility))
        {
            filteredPlots = filteredPlots.Where(h => h.CreditEligibility == model.CreditEligibility);
        }
           if (!string.IsNullOrEmpty(model.AdType))
        {
            filteredPlots = filteredPlots.Where(h => h.AdType == model.AdType);
        }

        model.PlotList = filteredPlots.ToList();

        return View("PlotList", model);
    }
    

public async Task<IActionResult> PlotDetails(int id)
{
    var plot = await _context.Plots
                              .Include(p => p.PlotImages)
                              .Include(p => p.AppUser) 
                              .FirstOrDefaultAsync(p => p.PlotId == id);
                              

    if (plot == null)
    {
        return NotFound();
    }

    var viewModel = new RealEstateViewModel
    {
        Plot = plot,
        PlotImagess = plot.PlotImages?.ToList()
    };

    return View(viewModel);
}
 
 [HttpGet]
 [Authorize]
 public async Task<IActionResult> PlotEdit(int id)
 {
    var plot = await _context.Plots.FindAsync(id);
    if (plot == null)
    {
        return NotFound();
    }
    var model = new PlotEditViewModel
    {
        AdNumber = Guid.NewGuid(),
            PlotType = plot.PlotType,
            PlotPrice = plot.PlotPrice,
            PlotTitle = plot.PlotTitle,
            M2 = plot.M2,
            M2Price = plot.M2Price,
            TitleDeedStatus = plot.TitleDeedStatus,
            IslandNumber = plot.IslandNumber,
            ParcelNumber = plot.ParcelNumber,
            Country = plot.Country,
            Province = plot.Province,
            Active = plot.Active,
            PlotStatus = plot.PlotStatus,
            County = plot.County,
            AdType = plot.AdType,
            Explanation = plot.Explanation,
            Neighborhood = plot.Neighborhood,
            Street = plot.Street,
            CreditEligibility = plot.CreditEligibility,
            
    };
    return View(model);
 }
[HttpPost]
[Authorize]
public async Task<IActionResult> PlotEdit(int id , PlotEditViewModel model)
{
    var plot = await _context.Plots.FindAsync(id);
    if (plot == null)
    {
        return NotFound();
    }
        if(ModelState.IsValid)
        {
            plot.PlotTitle = model.PlotTitle;
             plot.PlotType = model.PlotType;
             plot.PlotPrice = model.PlotPrice;
             plot.PlotTitle = model.PlotTitle;
             plot.M2 = model.M2;
             plot.M2Price = model.M2Price;
             plot.TitleDeedStatus = model.TitleDeedStatus;
             plot.IslandNumber = model.IslandNumber;
             plot.ParcelNumber = model.ParcelNumber;
             plot.Country = model.Country;
             plot.Province = model.Province;
             plot.Active ="newAd";
             plot.PlotStatus = model.PlotStatus;
             plot.County = model.County;
             plot.AdType = model.AdType;
             plot.Explanation = model.Explanation;
             plot.Neighborhood = model.Neighborhood;
             plot.Street = model.Street;
             plot.CreditEligibility = model.CreditEligibility;
             
             _context.Plots.Update(plot);
             await _context.SaveChangesAsync();
             return RedirectToAction("MyAd","Identity");
        }
        return View(model);
}
    
    }
}

RealEstate/RealEstate/Views/Home/AdForwarding.cshtml
<div class="card-body" style="display: flex; justify-content: space-between; align-items: center; margin-top:10rem;">

    <a asp-controller="Plot" asp-action="PlotAdd">
        <div class="card" style="flex: 1; text-align: center; width: 40rem; margin-left: -10%; position: relative;">
            <img style="width: 100%;" src="/img/indeximg/931047674a2b0592cb521f702b9566ee.jpg" alt="Açıklama">
            <p style="position: absolute; margin-left:1%; margin-top: 1%; padding: 15px; font-size: 24px; color: white; background: rgba(0, 0, 0, 0.7); border-radius: 8px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); font-weight: bold;">
               Arsa İlanı Ver
            </p>
        </div>
    </a>

    <a asp-controller="House" asp-action="HouseAdd">
        <div class="card" style="flex: 1; text-align: center; width: 40rem; margin-left: 10%; position: relative;">
            <img style="width: 100%;" src="/img/indeximg/pexels-photo-106399.jpeg" alt="Açıklama">
            <p style="position: absolute; margin-left:1%; margin-top: 1%; padding: 15px; font-size: 24px; color: white; background: rgba(0, 0, 0, 0.7); border-radius: 8px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); font-weight: bold;">
                Ev İlanı Ver
            </p>
        </div>
    </a>

</div>
</div>

</div>

RealEstate/RealEstate/Views/Home/Index.cshtml
@model RealEstate.ViewModels.RealEstateViewModel
@{
    ViewData["Title"] = "İstanbul Emlak";
}
<style>
  body {
      font-family: Helvetica, sans-serif;
      background-color: #f8f9fa; 
      margin: 0;
  }

  .card {
      border: 1px solid #ddd; 
      border-radius: 8px; 
      box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); 
      transition: transform 0.2s; 
  }

  .card:hover {
      transform: scale(1.05); 
  }

  .card-header {
      font-size: 24px;
      text-align: center;
      font-weight: bold;
      color: black; 
      padding: 10px;
      border-radius: 8px 8px 0 0; 
  }

  .house-card {
      width: 18rem; 
      margin: 1rem; 
      display: inline-block; 
      vertical-align: top; 
  }

  .card-body {
      padding: 15px; 
  }

  img {
      border-radius: 8px; 
  }

  .card-text {
      font-size: 18px; 
      font-weight: bold; 
  }

  .card p {
      margin: 0.5rem 0; 
  }
</style>
<div style="margin-left: -5%">
<div style="margin-left: auto;margin-right: auto; display:flex; width: 90em;">
<div class="card" style="width: 90rem; height: 49rem;  margin-top: 1%;">
    <div class="card-header" style="text-align: center; font-size: 28px; padding: 20px 0; background-color: #f8f9fa; font-weight: bold;">
        Yatırımınız Size Bir Tık Uzakta
    </div>

    <div class="card-body" style="display: flex; justify-content: space-between; align-items: center;">

        <a asp-controller="Plot" asp-action="PlotList">
            <div class="card" style="flex: 1; text-align: center; width: 40rem; margin-left: 5%; position: relative;">
                <img style="width: 100%;" src="/img/indeximg/931047674a2b0592cb521f702b9566ee.jpg" alt="Açıklama">
                <p style="position: absolute; margin-left:1%; margin-top: 1%; padding: 15px; font-size: 24px; color: white; background: rgba(0, 0, 0, 0.7); border-radius: 8px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); font-weight: bold;">
                    Yarınların İçin <br> Bugün Çalışmaya <br> Başla
                </p>
            </div>
        </a>

        <a asp-controller="House" asp-action="HouseList">
            <div class="card" style="flex: 1; text-align: center; width: 40rem; margin-left: -5%; position: relative;">
                <img style="width: 100%;" src="/img/indeximg/pexels-photo-106399.jpeg" alt="Açıklama">
                <p style="position: absolute; margin-left:1%; margin-top: 1%; padding: 15px; font-size: 24px; color: white; background: rgba(0, 0, 0, 0.7); border-radius: 8px; box-shadow: 0px 4px 8px rgba(0, 0, 0, 0.3); font-weight: bold;">
                    Yarınların İçin <br> Bugün Çalışmaya <br> Başla
                </p>
            </div>
        </a>

    </div>
</div>

</div>

<div class="card" style="width: 90rem; margin: 20px auto; padding: 20px;">
    <div class="card-header" style="font-size: 22px;">Yeni Evler</div>
    <div class="d-flex flex-wrap justify-content-">
        @foreach(var house in Model.HouseList)
        {
            <a  asp-controller="House" asp-action="HouseDetails" asp-route-id="@house.HouseId" style="text-decoration: none; color: black;">
                <div class="house-card">
                    <div class="card">
                        <img src="@house.PromotionalPicture" alt="Tanıtım Resmi" style="max-width: 100%; height: 15rem;" />
                        <div class="card-body">
                            <p class="card-text">@house.AdTitle</p>
                            <p>İlçe: @house.County</p>
                            <p>Fiyat: @house.Price</p>
                            <p>Oda Sayısı: @house.NumberOfRooms</p>
                            <p>Net m2: @house.m2n</p>
                        </div>
                    </div>
                </div>
            </a>
        }
    </div>
</div>

<div class="card" style="width: 90rem; margin: 20px auto; padding: 20px;">
    <div class="card-header" style="font-size: 22px;">Yeni Arsalar</div>
    <div class="d-flex flex-wrap justify-content-">
        @foreach(var plot in Model.PlotList)
        {
            <a  asp-controller="Plot" asp-action="PlotDetails" asp-route-id="@plot.PlotId" style="text-decoration: none; color: black;">
                <div class="house-card">
                    <div class="card">
                        <img src="~/plotimages/@plot.PromotionalPicture" alt="Tanıtım Resmi" style="width: 100%; height: auto; max-height: 15.6rem; object-fit: cover; margin-left: 2%;" />

                        <div class="card-body">
                            <p class="card-text">@plot.PlotTitle</p>
                            <li>İlçe: @plot.County</li>
                            <li>Fiyat: @plot.PlotPrice ₺</li>
                            <li>Arsa Durumu: @plot.PlotType</li>
                            <li>M²: @plot.M2</li>
                        </div>
                    </div>
                </div>
            </a>
        }
    </div>
</div>
</div>